language: node_js
node_js:
  - '10'

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        # - commitlint-travis
        - yarn test
        - yarn test:integration

    - stage: deploy
      script:
        - yarn build
        - yarn build:documentation
        - yarn semantic-release

cache: yarn
